spring.application.name=taskManagement
#spring.datasource.url=jdbc:postgresql://postgres-spring.czcyacyiudps.ap-south-1.rds.amazonaws.com:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=#Thanos2502
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secretKey = ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay
